import Head from 'next/head';
import Timer from '../components/Timer';
import Settings from '../components/Settings';
import Navbar from '../components/Navbar';
import SettingsContext from '../store/SettingsContext';
import { useState } from 'react';

export default function Home() {
  const [showSettings, setShowSetting] = useState(true);
  const [workMinutes, setWorkMinutes] = useState(45);
  const [breakMinutes, setBreakMinutes] = useState(15);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='index'>
        <SettingsContext.Provider
          value={{
            showSettings,
            setShowSetting,
            workMinutes,
            breakMinutes,
            setWorkMinutes,
            setBreakMinutes,
          }}
        >
          <Navbar className='index__navbar' />
          <div className='index__mid'>{showSettings ? <Settings /> : <Timer />}</div>
        </SettingsContext.Provider>
      </main>
      <footer></footer>
    </div>
  );
}
