import Head from 'next/head';
import Timer from '../components/Timer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <Timer />
      </main>

      <footer></footer>
    </div>
  );
}
